#Todos los valores se obtuvieron a partir de la comparaciones realizadas entre las mediciones del tótem con las de una termocupla y un higrómetro (HTC-1).

def ajustarValoresTemperatura(temperaturaC, hora):
    temperaturaAjustada = 0

    if hora == 5:
        if (temperaturaC <= 13):
            temperaturaAjustada = temperaturaC
        elif (13 < temperaturaC) and (temperaturaC <= 14):
            temperaturaAjustada = temperaturaC - 0.5
        elif (14 < temperaturaC) and (temperaturaC <= 15):
            temperaturaAjustada = temperaturaC - 1.5
        elif (15 < temperaturaC) and (temperaturaC <= 16):
            temperaturaAjustada = temperaturaC - 2.5
        elif (16 < temperaturaC) and (temperaturaC <= 17):
            temperaturaAjustada = temperaturaC - 3.5
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            temperaturaAjustada = temperaturaC - 4.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            temperaturaAjustada = temperaturaC - 5.5
        else:
            temperaturaAjustada = temperaturaC - 6.5

    elif hora == 6:
        if (temperaturaC <= 13):
            temperaturaAjustada = temperaturaC
        elif (13 < temperaturaC) and (temperaturaC <= 14):
            temperaturaAjustada = temperaturaC - 0.5
        elif (14 < temperaturaC) and (temperaturaC <= 15):
            temperaturaAjustada = temperaturaC - 1.5
        elif (15 < temperaturaC) and (temperaturaC <= 16):
            temperaturaAjustada = temperaturaC - 2.5
        elif (16 < temperaturaC) and (temperaturaC <= 17):
            temperaturaAjustada = temperaturaC - 3.5
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            temperaturaAjustada = temperaturaC - 4.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            temperaturaAjustada = temperaturaC - 5.5
        elif (19 < temperaturaC) and (temperaturaC <= 21):
            temperaturaAjustada = temperaturaC - 6.5
        elif (21 < temperaturaC) and (temperaturaC <= 22):
            temperaturaAjustada = temperaturaC - 7.5
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            temperaturaAjustada = temperaturaC - 8.5
        else:
            temperaturaAjustada = temperaturaC - 9.5

    elif hora == 7:
        if (temperaturaC <= 14):
            temperaturaAjustada = temperaturaC
        elif (14 < temperaturaC) and (temperaturaC <= 15):
            temperaturaAjustada = temperaturaC - 0.5
        elif (15 < temperaturaC) and (temperaturaC <= 16):
            temperaturaAjustada = temperaturaC - 1.5
        elif (16 < temperaturaC) and (temperaturaC <= 17):
            temperaturaAjustada = temperaturaC - 2.5
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            temperaturaAjustada = temperaturaC - 3.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            temperaturaAjustada = temperaturaC - 4.5
        elif (19 < temperaturaC) and (temperaturaC <= 21):
            temperaturaAjustada = temperaturaC - 5.5
        elif (21 < temperaturaC) and (temperaturaC <= 22):
            temperaturaAjustada = temperaturaC - 6.5
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            temperaturaAjustada = temperaturaC - 7
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 7.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 8.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 9.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 10.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 11.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 12.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 13.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 14.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 15.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 16.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 17.5
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 18.5
        else:
            temperaturaAjustada = temperaturaC - 19.5
    
    elif hora == 8:
        if (temperaturaC <= 16):
            temperaturaAjustada = temperaturaC
        elif (16 < temperaturaC) and (temperaturaC <= 17):
            temperaturaAjustada = temperaturaC - 0.5
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            temperaturaAjustada = temperaturaC - 1.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            temperaturaAjustada = temperaturaC - 2.5
        elif (19 < temperaturaC) and (temperaturaC <= 20):
            temperaturaAjustada = temperaturaC - 3.5
        elif (20 < temperaturaC) and (temperaturaC <= 21):
            temperaturaAjustada = temperaturaC - 4.5
        elif (21 < temperaturaC) and (temperaturaC <= 22):
            temperaturaAjustada = temperaturaC - 5.5
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            temperaturaAjustada = temperaturaC - 6.5
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 7
        elif (24 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 7.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 8.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 9.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 10.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 11.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 12.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 13.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 14.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 15.5
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 16.5
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 17.5
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 18.5
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 19.5
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 20.5
        else:
            temperaturaAjustada = temperaturaC - 21.5
    
    elif hora == 9:
        if (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 4
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 6
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 7.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 8.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 10.3
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 11.3
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 12.3
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 13.3
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 13.6
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 14.5
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 15.5
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 16.5
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 17.5
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 18.6
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 20
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 21
        elif (41 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 22
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 23
        else:
            temperaturaAjustada = temperaturaC - 23.5

    elif hora == 10:
        if (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 5.7
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 6.3
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 7.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 8.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 9.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 10.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 11.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 12.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 13.5
        elif (33 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 14
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 14.5
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 15.5
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 15.88
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 16.9
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 17.5
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 18
        elif (41 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 19
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 20
        elif (43 < temperaturaC) and (temperaturaC <= 43.5):
            temperaturaAjustada = temperaturaC - 21
        elif (43.5 < temperaturaC) and (temperaturaC <= 44):
            temperaturaAjustada = temperaturaC - 22
        elif (44 < temperaturaC) and (temperaturaC <= 44.5):
            temperaturaAjustada = temperaturaC - 23
        elif (44.5 < temperaturaC) and (temperaturaC <= 45):
            temperaturaAjustada = temperaturaC - 24
        elif (45 < temperaturaC) and (temperaturaC <= 45.5):
            temperaturaAjustada = temperaturaC - 25
        elif (45.5 < temperaturaC) and (temperaturaC <= 46):
            temperaturaAjustada = temperaturaC - 26
        else:
            temperaturaAjustada = temperaturaC - 26.7

    elif hora == 11:
        if (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 5.1
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 6.43
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 8
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 8.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 9
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 9.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 10
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 10.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 11
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 11.5
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 12
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 12.8
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 13.6
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 14.5
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 15
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 15.5
        elif (41 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 16.5
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 17.5
        elif (43 < temperaturaC) and (temperaturaC <= 44):
            temperaturaAjustada = temperaturaC - 18.5
        elif (44 < temperaturaC) and (temperaturaC <= 44.5):
            temperaturaAjustada = temperaturaC - 19.5
        else:
            temperaturaAjustada = temperaturaC - 20.5

    elif hora == 12:
        if (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 4.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 5.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 6
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 6.5
        elif (28 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 7
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 7.5
        elif (31 < temperaturaC) and (temperaturaC <= 31.5):
            temperaturaAjustada = temperaturaC - 8.75
        elif (31.5 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 9.8
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 10.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 11
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 12
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 12.5
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 13.5
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 14.5
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 15.5
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 16.5
        elif (40 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 17.5
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 18.5
        elif (43 < temperaturaC) and (temperaturaC <= 44):
            temperaturaAjustada = temperaturaC - 19.5
        elif (44 < temperaturaC) and (temperaturaC <= 45):
            temperaturaAjustada = temperaturaC - 20.5
        elif (45 < temperaturaC) and (temperaturaC <= 46):
            temperaturaAjustada = temperaturaC - 21.5
        elif (46 < temperaturaC) and (temperaturaC <= 47):
            temperaturaAjustada = temperaturaC - 22.5
        elif (47 < temperaturaC) and (temperaturaC <= 48):
            temperaturaAjustada = temperaturaC - 23.5
        elif (48 < temperaturaC) and (temperaturaC <= 49):
            temperaturaAjustada = temperaturaC - 24.5
        elif (49 < temperaturaC) and (temperaturaC <= 50):
            temperaturaAjustada = temperaturaC - 25.5
        elif (50 < temperaturaC) and (temperaturaC <= 51):
            temperaturaAjustada = temperaturaC - 26.5
        else:
            temperaturaAjustada = temperaturaC - 27.5

    elif hora == 13:
        if (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 1.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 2.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 3.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 4.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 5.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 6.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 7
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 7.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 8.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 9
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 10
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 10.5
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 11.5
        elif (36 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 12.5
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 13.75
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 15
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 16
        elif (41 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 17
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 18
        elif (43 < temperaturaC) and (temperaturaC <= 44):
            temperaturaAjustada = temperaturaC - 19.25
        elif (44 < temperaturaC) and (temperaturaC <= 45):
            temperaturaAjustada = temperaturaC - 20.5
        elif (45 < temperaturaC) and (temperaturaC <= 46):
            temperaturaAjustada = temperaturaC - 21.5
        elif (46 < temperaturaC) and (temperaturaC <= 47):
            temperaturaAjustada = temperaturaC - 22.5
        elif (47 < temperaturaC) and (temperaturaC <= 48):
            temperaturaAjustada = temperaturaC - 23.5
        elif (48 < temperaturaC) and (temperaturaC <= 49):
            temperaturaAjustada = temperaturaC - 24.5
        elif (49 < temperaturaC) and (temperaturaC <= 50):
            temperaturaAjustada = temperaturaC - 25.5
        elif (50 < temperaturaC) and (temperaturaC <= 51):
            temperaturaAjustada = temperaturaC - 26.5
        else:
            temperaturaAjustada = temperaturaC - 27.5
    
    elif hora == 14:
        if (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 1.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 2.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 3.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 4.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 5.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 6.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 7
        elif (30 < temperaturaC) and (temperaturaC <= 31.5):
            temperaturaAjustada = temperaturaC - 7.5
        elif (31.5 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 8
        elif (32 < temperaturaC) and (temperaturaC <= 32.5):
            temperaturaAjustada = temperaturaC - 8.5
        elif (32.5 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 9
        elif (33 < temperaturaC) and (temperaturaC <= 33.5):
            temperaturaAjustada = temperaturaC - 10
        elif (33.5 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 11
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 12
        elif (35 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 12.5
        elif (37 < temperaturaC) and (temperaturaC <= 37.5):
            temperaturaAjustada = temperaturaC - 13
        elif (37.5 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 13.5
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 14.5
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 15.5
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 16.5
        elif (41 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 17
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 18
        elif (43 < temperaturaC) and (temperaturaC <= 44):
            temperaturaAjustada = temperaturaC - 19.5
        elif (44 < temperaturaC) and (temperaturaC <= 45):
            temperaturaAjustada = temperaturaC - 20.5
        elif (45 < temperaturaC) and (temperaturaC <= 46):
            temperaturaAjustada = temperaturaC - 21.5
        elif (46 < temperaturaC) and (temperaturaC <= 47):
            temperaturaAjustada = temperaturaC - 22.5
        elif (47 < temperaturaC) and (temperaturaC <= 48):
            temperaturaAjustada = temperaturaC - 23.5
        elif (48 < temperaturaC) and (temperaturaC <= 49):
            temperaturaAjustada = temperaturaC - 24.5
        elif (49 < temperaturaC) and (temperaturaC <= 50):
            temperaturaAjustada = temperaturaC - 25.5
        elif (50 < temperaturaC) and (temperaturaC <= 51):
            temperaturaAjustada = temperaturaC - 26.5
        else:
            temperaturaAjustada = temperaturaC - 27.5

    elif hora == 15:
        if (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 0.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 1.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 2.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 3.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 4.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 5.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 6.5
        elif (30 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 7.6
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 8.6
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 9.6
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 10.5
        elif (35 < temperaturaC) and (temperaturaC <= 35.1):
            temperaturaAjustada = temperaturaC - 10.84
        elif (35.1 < temperaturaC) and (temperaturaC <= 35.2):
            temperaturaAjustada = temperaturaC - 11
        elif (35.2 < temperaturaC) and (temperaturaC <= 35.3):
            temperaturaAjustada = temperaturaC - 11.17
        elif (35.3 < temperaturaC) and (temperaturaC <= 35.4):
            temperaturaAjustada = temperaturaC - 11.34
        elif (35.4 < temperaturaC) and (temperaturaC <= 35.5):
            temperaturaAjustada = temperaturaC - 11.5
        elif (35.5 < temperaturaC) and (temperaturaC <= 35.6):
            temperaturaAjustada = temperaturaC - 11.67
        elif (35.6 < temperaturaC) and (temperaturaC <= 35.7):
            temperaturaAjustada = temperaturaC - 11.83
        elif (35.7 < temperaturaC) and (temperaturaC <= 35.8):
            temperaturaAjustada = temperaturaC - 12
        elif (35.8 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 12.16
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 12.5
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 13.5
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 14.5
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 15.5
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 16.5
        elif (41 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 17.5
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 18.5
        elif (43 < temperaturaC) and (temperaturaC <= 44):
            temperaturaAjustada = temperaturaC - 19.5
        elif (44 < temperaturaC) and (temperaturaC <= 45):
            temperaturaAjustada = temperaturaC - 20
        elif (45 < temperaturaC) and (temperaturaC <= 46):
            temperaturaAjustada = temperaturaC - 21
        elif (46 < temperaturaC) and (temperaturaC <= 47):
            temperaturaAjustada = temperaturaC - 22.5
        elif (47 < temperaturaC) and (temperaturaC <= 48):
            temperaturaAjustada = temperaturaC - 23.5
        elif (48 < temperaturaC) and (temperaturaC <= 49):
            temperaturaAjustada = temperaturaC - 24.5
        elif (49 < temperaturaC) and (temperaturaC <= 50):
            temperaturaAjustada = temperaturaC - 25.5
        elif (50 < temperaturaC) and (temperaturaC <= 51):
            temperaturaAjustada = temperaturaC - 26.5
        else:
            temperaturaAjustada = temperaturaC - 27.5

    elif hora == 16:
        if (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 1.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 3
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 4.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 5.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 6
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 6.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 7.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 8.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 9.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 11
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 12
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 12.5
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 13.5
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 14
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 14.5
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 15.5
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 17
        elif (41 < temperaturaC) and (temperaturaC <= 42):
            temperaturaAjustada = temperaturaC - 18
        elif (42 < temperaturaC) and (temperaturaC <= 43):
            temperaturaAjustada = temperaturaC - 19
        elif (43 < temperaturaC) and (temperaturaC <= 44):
            temperaturaAjustada = temperaturaC - 19.5
        elif (44 < temperaturaC) and (temperaturaC <= 45):
            temperaturaAjustada = temperaturaC - 20.5
        elif (45 < temperaturaC) and (temperaturaC <= 46):
            temperaturaAjustada = temperaturaC - 21
        elif (46 < temperaturaC) and (temperaturaC <= 47):
            temperaturaAjustada = temperaturaC - 22
        elif (47 < temperaturaC) and (temperaturaC <= 48):
            temperaturaAjustada = temperaturaC - 23
        elif (48 < temperaturaC) and (temperaturaC <= 49):
            temperaturaAjustada = temperaturaC - 24
        elif (49 < temperaturaC) and (temperaturaC <= 50):
            temperaturaAjustada = temperaturaC - 25
        elif (50 < temperaturaC) and (temperaturaC <= 51):
            temperaturaAjustada = temperaturaC - 26
        else:
            temperaturaAjustada = temperaturaC - 27
    
    elif hora == 17:
        if (temperaturaC <= 20):
            temperaturaAjustada = temperaturaC
        elif (20 < temperaturaC) and (temperaturaC <= 21):
            temperaturaAjustada = temperaturaC - 0.5
        elif (21 < temperaturaC) and (temperaturaC <= 22):
            temperaturaAjustada = temperaturaC - 1.5
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            temperaturaAjustada = temperaturaC - 2
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 2.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 3.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 4.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 6
        elif (27 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 6.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 7.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 9
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 10
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 11.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 12.5
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 13.5
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 14.5
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 15.5
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            temperaturaAjustada = temperaturaC - 16.5
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            temperaturaAjustada = temperaturaC - 17.5
        elif (39 < temperaturaC) and (temperaturaC <= 40):
            temperaturaAjustada = temperaturaC - 18.5
        elif (40 < temperaturaC) and (temperaturaC <= 41):
            temperaturaAjustada = temperaturaC - 19.5
        else:
            temperaturaAjustada = temperaturaC - 20.5
    
    elif hora == 18:
        if (temperaturaC <= 17):
            temperaturaAjustada = temperaturaC
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            temperaturaAjustada = temperaturaC - 0.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            temperaturaAjustada = temperaturaC - 1
        elif (19 < temperaturaC) and (temperaturaC <= 20):
            temperaturaAjustada = temperaturaC - 2
        elif (20 < temperaturaC) and (temperaturaC <= 21):
            temperaturaAjustada = temperaturaC - 3
        elif (21 < temperaturaC) and (temperaturaC <= 22):
            temperaturaAjustada = temperaturaC - 3.5
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            temperaturaAjustada = temperaturaC - 4
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 4.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 6.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 7.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 8.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 9.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 10.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 11.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 12.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 13.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 14.5
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 15
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 16
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 17
        else:
            temperaturaAjustada = temperaturaC - 17.5

    elif hora == 19:
        if (temperaturaC <= 17):
            temperaturaAjustada = temperaturaC
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            temperaturaAjustada = temperaturaC - 0.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            temperaturaAjustada = temperaturaC - 1.5
        elif (19 < temperaturaC) and (temperaturaC <= 21):
            temperaturaAjustada = temperaturaC - 2.5
        elif (21 < temperaturaC) and (temperaturaC <= 22):
            temperaturaAjustada = temperaturaC - 3.5
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            temperaturaAjustada = temperaturaC - 4.5
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 5.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 6.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 7.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 8.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 9.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 10.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 11.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 12.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 13.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 14.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 15
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 15.5
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 16
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 16.5
        else:
            temperaturaAjustada = temperaturaC - 17

    else:
        if (temperaturaC <= 16):
            temperaturaAjustada = temperaturaC
        elif (16 < temperaturaC) and (temperaturaC <= 17):
            temperaturaAjustada = temperaturaC - 0.5
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            temperaturaAjustada = temperaturaC - 1.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            temperaturaAjustada = temperaturaC - 2.5
        elif (19 < temperaturaC) and (temperaturaC <= 20):
            temperaturaAjustada = temperaturaC - 3.5
        elif (20 < temperaturaC) and (temperaturaC <= 22):
            temperaturaAjustada = temperaturaC - 4.5
        elif (22 < temperaturaC) and (temperaturaC <= 24):
            temperaturaAjustada = temperaturaC - 5.5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            temperaturaAjustada = temperaturaC - 6.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            temperaturaAjustada = temperaturaC - 7.5
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            temperaturaAjustada = temperaturaC - 8.5
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            temperaturaAjustada = temperaturaC - 9.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            temperaturaAjustada = temperaturaC - 10.5
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            temperaturaAjustada = temperaturaC - 11.5
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            temperaturaAjustada = temperaturaC - 12.5
        elif (31 < temperaturaC) and (temperaturaC <= 32):
            temperaturaAjustada = temperaturaC - 13.5
        elif (32 < temperaturaC) and (temperaturaC <= 33):
            temperaturaAjustada = temperaturaC - 14.5
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            temperaturaAjustada = temperaturaC - 15
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            temperaturaAjustada = temperaturaC - 15.5
        elif (35 < temperaturaC) and (temperaturaC <= 36):
            temperaturaAjustada = temperaturaC - 16
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            temperaturaAjustada = temperaturaC - 16.5
        else:
            temperaturaAjustada = temperaturaC - 17
    
    return temperaturaAjustada


def ajustarValoresHumedad(temperaturaC, humedad, hora):
    humedadAjustada = 0

    if hora == 5:
        if (temperaturaC <= 15):
            humedadAjustada = humedad
        elif (15 < temperaturaC) and (temperaturaC <= 16):
            humedadAjustada = humedad + 2.5
        elif (16 < temperaturaC) and (temperaturaC <= 17):
            humedadAjustada = humedad + 6
        elif (17 < temperaturaC) and (temperaturaC <= 18):
            humedadAjustada = humedad + 9.6
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            humedadAjustada = humedad + 13.1
        else:
            humedadAjustada = humedad + 16.6

    elif hora == 6:
        if (temperaturaC <= 15):
            humedadAjustada = humedad + 1.65
        elif (15 < temperaturaC) and (temperaturaC <= 16):
            humedadAjustada = humedad + 4.15
        elif (16 < temperaturaC) and (temperaturaC <= 17):
            humedadAjustada = humedad + 7.65
        elif (17 < temperaturaC) and (temperaturaC <= 22):
            humedadAjustada = humedad + 11.12
        else:
            humedadAjustada = humedad + 13.62

    elif hora == 7:
        if (temperaturaC <= 18):
            humedadAjustada = humedad + 13.5
        elif (18 < temperaturaC) and (temperaturaC <= 19):
            humedadAjustada = humedad + 12
        elif (19 < temperaturaC) and (temperaturaC <= 23):
            humedadAjustada = humedad + 10.5
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            humedadAjustada = humedad + 9
        elif (24 < temperaturaC) and (temperaturaC <= 24.5):
            humedadAjustada = humedad + 15.75
        elif (24.5 < temperaturaC) and (temperaturaC <= 25):
            humedadAjustada = humedad + 17.3
        else:
            humedadAjustada = humedad + 18.5
    
    elif hora == 8:
        if (temperaturaC <= 20):
            humedadAjustada = humedad + 9
        elif (20 < temperaturaC) and (temperaturaC <= 21):
            humedadAjustada = humedad + 12
        elif (21 < temperaturaC) and (temperaturaC <= 22):
            humedadAjustada = humedad + 10
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            humedadAjustada = humedad + 5.5
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            humedadAjustada = humedad + 8
        elif (24 < temperaturaC) and (temperaturaC <= 26):
            humedadAjustada = humedad + 12
        elif (26 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 15.06
        elif (29 < temperaturaC) and (temperaturaC <= 33):
            humedadAjustada = humedad + 19.82
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            humedadAjustada = humedad + 25
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            humedadAjustada = humedad + 29
        else:
            humedadAjustada = humedad + 33.03

    elif hora == 9:
        if (temperaturaC <= 26):
            humedadAjustada = humedad + 0
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            humedadAjustada = humedad + 4
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            humedadAjustada = humedad + 8
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 12
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            humedadAjustada = humedad + 16
        elif (30 < temperaturaC) and (temperaturaC <= 33):
            humedadAjustada = humedad + 20.6
        elif (33 < temperaturaC) and (temperaturaC <= 36):
            humedadAjustada = humedad + 24.67
        elif (36 < temperaturaC) and (temperaturaC <= 37):
            humedadAjustada = humedad + 26.4
        elif (37 < temperaturaC) and (temperaturaC <= 38):
            humedadAjustada = humedad + 28.5
        elif (38 < temperaturaC) and (temperaturaC <= 43):
            humedadAjustada = humedad + 30.83
        else:
            humedadAjustada = humedad + 33.33
    
    elif hora == 10:
        if (temperaturaC <= 25):
            humedadAjustada = humedad + 4
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            humedadAjustada = humedad + 6.8
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            humedadAjustada = humedad + 8.7
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            humedadAjustada = humedad + 13
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 16
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            humedadAjustada = humedad + 19
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            humedadAjustada = humedad + 21.85
        elif (31 < temperaturaC) and (temperaturaC <= 39):
            humedadAjustada = humedad + 24.65
        elif (39 < temperaturaC) and (temperaturaC <= 43):
            humedadAjustada = humedad + 26.78
        else:
            humedadAjustada = humedad + 30.17

    elif hora == 11:
        if (temperaturaC <= 27):
            humedadAjustada = humedad + 7
        elif (27 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 9.44
        elif (29 < temperaturaC) and (temperaturaC <= 32):
            humedadAjustada = humedad + 12.6
        elif (32 < temperaturaC) and (temperaturaC <= 35):
            humedadAjustada = humedad + 13.67
        elif (35 < temperaturaC) and (temperaturaC <= 38):
            humedadAjustada = humedad + 18.25
        elif (38 < temperaturaC) and (temperaturaC <= 39):
            humedadAjustada = humedad + 20.40
        elif (39 < temperaturaC) and (temperaturaC <= 41):
            humedadAjustada = humedad + 21.6
        elif (41 < temperaturaC) and (temperaturaC <= 43):
            humedadAjustada = humedad + 23.98
        else:
            humedadAjustada = humedad + 25.5

    elif hora == 12:
        if (temperaturaC <= 28):
            humedadAjustada = humedad + 8.55
        elif (28 < temperaturaC) and (temperaturaC <= 30):
            humedadAjustada = humedad + 9.55
        elif (30 < temperaturaC) and (temperaturaC <= 32):
            humedadAjustada = humedad + 10.56
        elif (32 < temperaturaC) and (temperaturaC <= 34):
            humedadAjustada = humedad + 13.06
        elif (34 < temperaturaC) and (temperaturaC <= 36):
            humedadAjustada = humedad + 15.56
        elif (36 < temperaturaC) and (temperaturaC <= 38):
            humedadAjustada = humedad + 18.06
        elif (38 < temperaturaC) and (temperaturaC <= 44):
            humedadAjustada = humedad + 20.78
        elif (44 < temperaturaC) and (temperaturaC <= 47):
            humedadAjustada = humedad + 22.97
        else:
            humedadAjustada = humedad + 25

    elif hora == 13:
        if (temperaturaC <= 29):
            humedadAjustada = humedad + 8.55
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            humedadAjustada = humedad + 9
        elif (30 < temperaturaC) and (temperaturaC <= 32):
            humedadAjustada = humedad + 10.36
        elif (32 < temperaturaC) and (temperaturaC <= 34):
            humedadAjustada = humedad + 12.5
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            humedadAjustada = humedad + 15
        elif (35 < temperaturaC) and (temperaturaC <= 37):
            humedadAjustada = humedad + 18.4
        elif (37 < temperaturaC) and (temperaturaC <= 39):
            humedadAjustada = humedad + 19.03
        elif (39 < temperaturaC) and (temperaturaC <= 41):
            humedadAjustada = humedad + 20.3
        elif (41 < temperaturaC) and (temperaturaC <= 43):
            humedadAjustada = humedad + 21.43
        elif (43 < temperaturaC) and (temperaturaC <= 44):
            humedadAjustada = humedad + 22.57
        elif (44 < temperaturaC) and (temperaturaC <= 46):
            humedadAjustada = humedad + 23.6
        else:
            humedadAjustada = humedad + 24.5

    elif hora == 14:
        if (temperaturaC <= 31):
            humedadAjustada = humedad + 8.5
        elif (31 < temperaturaC) and (temperaturaC <= 33):
            humedadAjustada = humedad + 9.68
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            humedadAjustada = humedad + 15
        elif (34 < temperaturaC) and (temperaturaC <= 35):
            humedadAjustada = humedad + 17.5
        elif (35 < temperaturaC) and (temperaturaC <= 40):
            humedadAjustada = humedad + 20
        elif (40 < temperaturaC) and (temperaturaC <= 42):
            humedadAjustada = humedad + 21.12
        else:
            humedadAjustada = humedad + 22.5

    elif hora == 15:
        if (temperaturaC <= 30):
            humedadAjustada = humedad + 9
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            humedadAjustada = humedad + 10.95
        elif (31 < temperaturaC) and (temperaturaC <= 33):
            humedadAjustada = humedad + 12.58
        elif (33 < temperaturaC) and (temperaturaC <= 34):
            humedadAjustada = humedad + 15
        elif (34 < temperaturaC) and (temperaturaC <= 40):
            humedadAjustada = humedad + 16
        elif (40 < temperaturaC) and (temperaturaC <= 42):
            humedadAjustada = humedad + 18
        elif (42 < temperaturaC) and (temperaturaC <= 45):
            humedadAjustada = humedad + 21.03
        else:
            humedadAjustada = humedad + 22.5

    elif hora == 16:
        if (temperaturaC <= 26):
            humedadAjustada = humedad + 7
        elif (26 < temperaturaC) and (temperaturaC <= 30):
            humedadAjustada = humedad + 10.06
        elif (30 < temperaturaC) and (temperaturaC <= 34):
            humedadAjustada = humedad + 16.3
        elif (34 < temperaturaC) and (temperaturaC <= 38):
            humedadAjustada = humedad + 17.53
        elif (38 < temperaturaC) and (temperaturaC <= 42):
            humedadAjustada = humedad + 20
        elif (42 < temperaturaC) and (temperaturaC <= 46):
            humedadAjustada = humedad + 22.63
        else:
            humedadAjustada = humedad + 25

    elif hora == 17:
        if (temperaturaC <= 24):
            humedadAjustada = humedad + 5
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            humedadAjustada = humedad + 7
        elif (25 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 9.19
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            humedadAjustada = humedad + 14.19
        elif (30 < temperaturaC) and (temperaturaC <= 33):
            humedadAjustada = humedad + 19.19
        elif (33 < temperaturaC) and (temperaturaC <= 35):
            humedadAjustada = humedad + 24.3
        elif (35 < temperaturaC) and (temperaturaC <= 41):
            humedadAjustada = humedad + 25.72
        else:
            humedadAjustada = humedad + 27.5

    elif hora == 18:
        if (temperaturaC <= 21):
            humedadAjustada = humedad + 3
        elif (21 < temperaturaC) and (temperaturaC <= 23):
            humedadAjustada = humedad + 4.5
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            humedadAjustada = humedad + 7.05
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            humedadAjustada = humedad + 11.5
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            humedadAjustada = humedad + 15.85
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            humedadAjustada = humedad + 16.96
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            humedadAjustada = humedad + 18.07
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 19.2
        elif (29 < temperaturaC) and (temperaturaC <= 30):
            humedadAjustada = humedad + 21.3
        elif (30 < temperaturaC) and (temperaturaC <= 31):
            humedadAjustada = humedad + 23.5
        elif (31 < temperaturaC) and (temperaturaC <= 36):
            humedadAjustada = humedad + 26
        else:
            humedadAjustada = humedad + 27

    elif hora == 19:
        if (temperaturaC <= 19):
            humedadAjustada = humedad + 1
        elif (19 < temperaturaC) and (temperaturaC <= 22):
            humedadAjustada = humedad + 2.68
        elif (22 < temperaturaC) and (temperaturaC <= 23):
            humedadAjustada = humedad + 8
        elif (23 < temperaturaC) and (temperaturaC <= 24):
            humedadAjustada = humedad + 11.8
        elif (24 < temperaturaC) and (temperaturaC <= 25):
            humedadAjustada = humedad + 14.8
        elif (25 < temperaturaC) and (temperaturaC <= 26):
            humedadAjustada = humedad + 15.76
        elif (26 < temperaturaC) and (temperaturaC <= 27):
            humedadAjustada = humedad + 16.73
        elif (27 < temperaturaC) and (temperaturaC <= 28):
            humedadAjustada = humedad + 17.5
        elif (28 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 22.05
        elif (29 < temperaturaC) and (temperaturaC <= 31):
            humedadAjustada = humedad + 26.6
        else:
            humedadAjustada = humedad + 28.6

    else:
        if (temperaturaC <= 17):
            humedadAjustada = humedad + 5
        elif (17 < temperaturaC) and (temperaturaC <= 23):
            humedadAjustada = humedad + 9.28
        elif (23 < temperaturaC) and (temperaturaC <= 26):
            humedadAjustada = humedad + 14.5
        elif (26 < temperaturaC) and (temperaturaC <= 29):
            humedadAjustada = humedad + 20
        else:
            humedadAjustada = humedad + 25.78

    return humedadAjustada